#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  1 14:31:31 2018

@author: bernardopaulsen
"""

import matplotlib.pyplot as plt
import numpy as np



class OLG():
    
    def __init__(self,
                 laststochastic = 1,
                 k = 4,
                 labda = 0.6,
                 bug = 1,
                 capital = 1,
                 theta = 0.36):
    
        self.laststochastic = laststochastic
        self.k = k
        self.labda = labda
        self.bug = bug
        self.capital = capital
        self.theta = theta
    
    def stochastic(self):
        
        return (1 - self.labda) + self.labda * self.laststochastic + np.random.normal(0,0.2)
    
    def update(self):
        
        self.laststochastic = self.bug
        
    def nextcapital(self):
        
        self.bug = self.stochastic()
        
        return self.k * self.bug * self.capital ** self.theta
        
        
    def timeseries(self,lenght):
        
        data = []
        
        for i in range(lenght):
            
            tiro = self.nextcapital()
            
            data.append(tiro)
            
            self.update
            
        plt.plot(data)
        plt.show()
        
modelo=OLG()

modelo.timeseries(100)
        
        

      
  #  def printing(self,lenght):
   #     
    #    data = []
        
     #   for i in range(lenght):
        
      #      self.bug = self.stochastic()
       #     
        #    print(self.bug)
         #   data.append(self.bug)
          #  self.update
            
     #   print(data)
    #    plt.plot(data)
   #     plt.show()
        
            

#modelo=OLG()

#modelo.printing(120)

