#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 14 14:10:04 2018

@author: bernardopaulsen
"""

import matplotlib.pyplot as plt
import numpy as np



class Solow():
    
    def __init__(self,
                 capital = 1,
                 labour = 1,
                 theta = 0.36,
                 tech = 1,
                 depreciation = 0.1,
                 savings = 0.2,
                 labourgrowth = 0.02):
    
        self.capital = capital
        self.labour = labour
        self.theta = theta
        self.tech = tech
        self.depreciation = depreciation
        self.savings = savings
        self.labourgrowth = labourgrowth
    
    def function(self):
        
        return self.capital ** self.theta * self.labour ** (1 - self.theta)
    
    def capitalPW(self):
        
        return self.capital / self.labour
    
    def nextcapital(self):
        
        return ((1 - self.depreciation) * self.capital + self.savings * self.tech * self.function())/(1 + self.labourgrowth)
    
    def nextlabour(self):
        
        return self.labour * self.labourgrowth
    
    def nexttech(self):
        
        return 1 * 2,71828182846 ** np.normalvariate(0,0.2)

        
        
    
# FIGURE 1.1    
modelo=Solow(capital = np.linspace(0,3,100))

plt.plot(modelo.capital, modelo.nextcapital())
plt.plot(modelo.capital,modelo.capital)
plt.show()